[2024-11-24T04:01:59.035+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: first_dag.inaccurate scheduled__2024-11-23T00:00:00+00:00 [queued]>
[2024-11-24T04:01:59.042+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: first_dag.inaccurate scheduled__2024-11-23T00:00:00+00:00 [queued]>
[2024-11-24T04:01:59.043+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-11-24T04:01:59.052+0000] {taskinstance.py:2217} INFO - Executing <Task(BashOperator): inaccurate> on 2024-11-23 00:00:00+00:00
[2024-11-24T04:01:59.055+0000] {standard_task_runner.py:60} INFO - Started process 398 to run task
[2024-11-24T04:01:59.056+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'first_dag', 'inaccurate', 'scheduled__2024-11-23T00:00:00+00:00', '--job-id', '11', '--raw', '--subdir', 'DAGS_FOLDER/first_dag.py', '--cfg-path', '/tmp/tmp67ltb1e1']
[2024-11-24T04:01:59.057+0000] {standard_task_runner.py:88} INFO - Job 11: Subtask inaccurate
[2024-11-24T04:01:59.080+0000] {task_command.py:423} INFO - Running <TaskInstance: first_dag.inaccurate scheduled__2024-11-23T00:00:00+00:00 [running]> on host 08b9826fa440
[2024-11-24T04:01:59.114+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='first_dag' AIRFLOW_CTX_TASK_ID='inaccurate' AIRFLOW_CTX_EXECUTION_DATE='2024-11-23T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-11-23T00:00:00+00:00'
[2024-11-24T04:01:59.115+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-11-24T04:01:59.116+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', "echo 'inaccurate'"]
[2024-11-24T04:01:59.121+0000] {subprocess.py:86} INFO - Output:
[2024-11-24T04:01:59.123+0000] {subprocess.py:93} INFO - inaccurate
[2024-11-24T04:01:59.123+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-11-24T04:01:59.136+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=first_dag, task_id=inaccurate, execution_date=20241123T000000, start_date=20241124T040159, end_date=20241124T040159
[2024-11-24T04:01:59.153+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-11-24T04:01:59.162+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
